apiVersion: v1
kind: Secret
metadata:
  name: zipkin
  labels:
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app: {{ template "name" . }}
type: Opaque
Stringdata:
  elastic.password: {{ .Values.elastic.password }}
  elastic.user: {{  .Values.elastic.username }}